name: cloud_authenticator
description: "An authenticator app which saves your auth codes to the cloud."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  auto_route: ^9.2.0
  base32: ^2.1.3
  cloud_firestore: ^5.2.1
  dynamic_color: ^1.7.0
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  flutter_speed_dial: ^7.0.0
  freezed_annotation: ^2.4.1
  google_fonts: ^6.2.1
  json_annotation: ^4.8.1
  local_auth: ^2.2.0
  mobile_scanner: ^5.1.1
  otp: ^3.1.4
  qr_code_scanner: ^1.0.1
  riverpod_annotation: ^2.3.4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.9
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11
  auto_route_generator: ^9.0.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
