name: cloud_authenticator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  firebase_core: ^2.25.4
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.9
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11

flutter:
  uses-material-design: true
